import { IComment } from "./comments.interface";

export interface IProject {
    _id: string,
    company: string,
    dateCreated: Date,
    dateEdited: Date,
    projectType: string,
    houseAmount: string,
    projectName: string,
    client: string,
    street: string,
    city: string,
    postalCode: string,
    extraInfoAddress: string,
    lng: Number,
    lat: Number,
    name: string,
    tel: string,
    email: string,
    extraInfoContact: string,
    EpbReporter: string,
    ATest: string,
    v50Value: string,
    protectedVolume: string,
    EpbNumber: string,
    executor: string,
    datePlanned: Date,
    hourPlanned: string,
    status: string,
    comments: IComment[],
    mails: any[],
    calendarId: string,
    eventId: string,
    calendarLink: string,
    dateActive: Date,
}
